version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kirill123
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscription_db
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
